#!/bin/bash

help() {
   echo 'usage: ansible-show-secret yq-expression inventory-file-with-secret'
   echo '       ansible-show-secret --help'
   echo
   echo '   Example:'
   echo '       $ cat inventory/group_vars/all/samba-password'
   echo '       samba_pwd: !vault |'
   echo '                 $ANSIBLE_VAULT;1.1;AES256'
   echo '                 27313536676839633045586678353332333735663738623162633435646764768181920237272716'
   echo '                 [...]'
   echo
   echo '       $ ansible-show-secret .samba_pwd inventory/group_vars/all/samba-password'
   echo '       Decryption successful'
   echo '       s3cr3t'
   echo
   echo '       $ ansible-show-secret .samba_pwd inventory/group_vars/all/samba-password | cat'
   echo '       s3cr3t'
   echo
   echo "   ATTENTION: this uses mikefarah's yq"
   echo
   exit 1
}

[ "$1" == "--help" ] && help
[ "$1" == "" -o "$2" == "" ] && echo "ERROR: two parameters are required" >&1 && exit 1

set -e          # stop on error
set -u          # stop on undefined variable
set -o pipefail # stop part of pipeline failing

yq e "$1" "$2" | ansible-vault decrypt
