#!/bin/bash

help() {
  echo 'usage: brightness [percent]'
  echo 
  echo '    set panel brightness on intel chips in percent (default ist 60%)'
  exit
}

if [ "$1" == "--help" ]; then
   help
elif [ -z "$1" ]; then
   percent=60
else
   percent=$1
fi

max=$( cat /sys/class/backlight/intel_backlight/max_brightness )
want=$(( $max / 100 * $percent ))
sudo sh -c "echo $want > /sys/class/backlight/intel_backlight/brightness"
echo "set brightness to $percent"
