#!/bin/bash

help() {
  echo "$0 [percent]"
  echo 
  echo "    set brightness to percent (default ist 60%)"
}

if [ "$1" == "--help" ]; then
   help
elif [ -z "$1" ]; then
   percent=60
else
   percent=$1
fi

max=$( cat /sys/class/backlight/intel_backlight/max_brightness )
want=$(( $max / 100 * $percent ))
sudo sh -c "echo $want > /sys/class/backlight/intel_backlight/brightness"
echo "set brightness to $percent"
