#!/bin/bash

help() {
   echo 'usage: bromium'
   echo '       bromium --help'
   echo
   echo '    run chromium with an empty temporary profile'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

chromium50_bug="--disable-gpu"
# see
# * https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822170
# * https://groups.google.com/forum/?_escaped_fragment_=topic/qubes-users/bdU_oOUcO94#!topic/qubes-users/bdU_oOUcO94

if [ "$1" ]; then
  exec chromium $chromium50_bug --temp-profile --incognito "$@"
else
  exec chromium $chromium50_bug --temp-profile --incognito "about:blank"
fi
