#!/bin/bash

help() {
   echo 'usage: bromium'
   echo '       bromium --help'
   echo
   echo '    run chromium with an empty temporary profile'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

if [ "$1" ]; then
  exec chromium --temp-profile --incognito "$@"
else
  exec chromium --temp-profile --incognito "about:blank"
fi
