#!/bin/bash

help() {
   echo 'usage: bromium [--enable-cookies] [URL]'
   echo '       bromium --help'
   echo
   echo '    Run chromium with an empty temporary profile.'
   echo
   echo '    By default bromium will run in "incognito"'
   echo '    mode. If you want to allow cookies then'
   echo '    use --enable-cookies'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

chromium50_bug="--disable-gpu"
# see
# * https://bugs.debian.org/822170
# * https://groups.google.com/forum/?_escaped_fragment_=topic/qubes-users/bdU_oOUcO94#!topic/qubes-users/bdU_oOUcO94

tmp_user_dir=$( mktemp -d /tmp/bromium.XXXX )

# see http://peter.sh/experiments/chromium-command-line-switches/ for options

if [ "$1" == "--enable-cookies" ]; then
  incognito=""
  shift
else
  incognito="--incognito"
fi

if [ "$1" ]; then
  chromium $chromium50_bug --user-data-dir="$tmp_user_dir" --temp-profile --disable-notifications $incognito "$@"
else
  chromium $chromium50_bug --user-data-dir="$tmp_user_dir" --temp-profile --disable-notifications $incognito "about:blank"
fi

# be really sure that "$tmp_user_dir" contains a correct tmpdir
# before rm -rf /* or such
#
if [[ "$tmp_user_dir" =~ /tmp/bromium ]]; then
  rm -r "$tmp_user_dir"
else
  echo "hae? $tmp_user_dir"
fi
