#!/bin/bash

help() {
   echo 'usage: catnamed file ...'
   echo
   echo '    print name of file and then cat it'
   echo 
   exit
}

[ "$1" == "--help" ] && help

while [ "$1" != "" ]; do
   echo "===== $1 ====="
   echo
   cat "$1"
   echo
   shift
done
