#!/bin/bash

fullpath=`which $1`
if [ "$?" == 0 ]; then
   cat "$fullpath"
else
   location=`locate $1`
   if [ "$?" == 0 ]; then

      if [ `echo "$location"|wc -l` != 1 ]; then
         echo "Ambiguous - multiple matches found" >&2
         sleep 1
	 location=`echo "$location"|head -n 1`
      fi
      cat "$location"
   else

      echo "Sorry none found"
      exit -1
   fi
fi
