#!/bin/bash

help() {
   echo 'usage: cert-show (--help|certificate|--host host:port [--smtp|--postgres])'
   echo
   echo '    print all kinds of certificates'
   echo
   exit 1
}

[ "$1" == "--help" ] || [ "$1" == "" ] && help

if [ "$1" == "--host" ]; then
   [ "$2" == "" ] && help

   connection="$2"

   case "$3" in
      --smtp)     start_tls="-starttls smtp" ;;
      --postgres) start_tls="-starttls postgres" ;;
   esac

   echo "" | \
   openssl s_client -showcerts -connect $connection $start_tls | \
   openssl x509 -inform pem -noout -text

else
   CERT="$1"
   EXT=$( file_extension --lowercase "$CERT" )
   
   case "$EXT" in
      p7b)
            openssl pkcs7  -in "$CERT"
         ;;
      pfx|p12)
            openssl pkcs12 -in "$CERT" -nokeys
         ;;
      key)
            openssl rsa    -in "$CERT" -noout -text
         ;;
      csr)
            openssl req    -in "$CERT" -noout -text
         ;;
      crl)
            openssl crl    -in "$CERT" -noout -text -inform der
         ;;
      cer|der|crt|pem)
         if grep -q "BEGIN CERTIFICATE" "$CERT"; then
            # assume PEM format
            openssl x509   -in "$CERT" -noout -text -inform pem
         else
            # assume DER format
            openssl x509   -in "$CERT" -noout -text -inform der
         fi
         ;;
      *)
            openssl x509   -in "$CERT" -noout -text
         ;;
   esac
fi
