#!/bin/bash

help() {
   echo 'usage: cert-fingerprint certificate.crt'
   echo '       cert-fingerprint --help'
   echo
   echo '    print fingerprint of x509 certificate'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

openssl x509 -subject -dates -fingerprint -in "$1"
