#!/bin/bash
#
help() {
   echo 'usage: copy_file_to_clip [file]'
   echo
   echo 'copy file to clipboard (CTRL-V)'
   echo
   echo 'if no file is given, copies stdin'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

(
  if [ -z "$1" ]; then
    cat
  else
    cat "$1"
  fi
) | xclip -i -selection clipboard
