#!/bin/bash

help() {
   echo "copy arguments to clipboard (CTRL-V)"
   echo
   echo "usage: to_copy_args arg1 arg2 ..."
   echo
   echo "  if no argument is given, then copy stdin to clipboard"
   exit 1
}

[ "$1" == "--help" ] && help

# "echo -En" removes trailing newline
#
if [ "$1" != "" ]; then
  echo -En "$@"       | xclip -i -selection clipboard
else
  echo -En "$( cat )" | xclip -i -selection clipboard
fi
