#!/bin/bash

help() {
   echo 'usage: copy_args_to_clip arg1 arg2 ...'
   echo
   echo '    copy arguments to clipboard (CTRL-V)'
   echo
   echo '    if no argument is given, then copy stdin to clipboard'
   echo 
   exit 1
}

[ "$1" == "--help" ] && help

# "echo -En" removes trailing newline
#
if [ "$1" != "" ]; then
  echo -En "$@"       | xclip -i -selection clipboard
else
  echo -En "$( cat )" | xclip -i -selection clipboard
fi
