#!/bin/bash

help() {
   echo 'usage: copy_args_to_file file_name arg1 arg2 ...'
   echo
   echo '    copy arguments to file'
   echo
   echo '    if no argument is given, then copy stdin to clipboard'
   echo 
   exit 1
}

[ "$1" == "--help" ] && help

file="$1"
shift 1

echo "$@" > "$file"
