#!/bin/bash

help() {
   echo 'usage: copy_sel_to_clip'
   echo
   echo 'copy selection (mouse select) to clipboard (CTRL-V)'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

xclip -o | xclip -i -selection clipboard
