#!/bin/bash

help() {
   echo 'usage: dockerviz'
   echo '       dockerviz --help'
   echo
   echo '    Visualize docker image dependencies'
   echo
   echo '    Needs https://github.com/justone/dockviz'
   echo '    Uses geeqie'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

set -e          # stop on error
set -u          # stop on undefined variable
set -o pipefail # stop part of pipeline failing

echo "Generating the graph will take a while..."

tmpfile=`mktemp /tmp/dockviz.XXXXXX.png`
dockviz images -d | dot -Tpng -o "$tmpfile"
geeqie "$tmpfile"
rm "$tmpfile"
