#!/bin/bash


help() {
  echo 'usage: findhere SEARCH_STRING [OTHER_FIND_OPTIONS]'
  echo 
  echo '    will execute "find . -name "*SEARCH_STRING*" [OTHER_FIND_OPTIONS]"'
  echo 
  exit
}

[ "$1" == "--help" ] || [ "$1" == "" ] && help

name="$1"; shift

find . -name "*$name*" "$@"
