#!/bin/bash


help() {
   echo 'usage: firejail_save_all_ff_tabs'
   echo '       firejail_save_all_ff_tabs --help'
   echo
   echo "    Save all tabs of all firefoxes inside firejail"
   echo
   exit 1
}

[ "$1" == "--help" ] && help

set -e          # stop on error
set -u          # stop on undefined variable
set -o pipefail # stop part of pipeline failing

browsertabs_home="~/tmp/browsertabs/"
cd "$browsertabs_home"
new_browsertabs_dir="$browsertabs_home/$( mkdir-now --ignore-existing --script --ignore-existing )"
tmpdir="$( mktemp -d )"
cd "$tmpdir"

readarray -t jails < <( firejail --list | grep /usr/bin/firefox )

for jail_line in "${jails[@]}"; do
  jail=$( echo "$jail_line" | sed 's/:.*//' )
  mkdir "$new_browsertabs_dir/$jail"
  recovery_file="$(
    firejail --join=$jail bash -c 'stat --format %n ~/.mozilla/firefox/*.default-esr/sessionstore-backups/recovery.jsonlz4' )"
  firejail --get=$jail "$recovery_file"
  (
    echo "<html><body>"
    ff_tabs_list_in recovery.jsonlz4 '<a href="%(url)s">%(title)s</a><br>'
    echo "</body></html>"
  ) > "$new_browsertabs_dir/$jail/tabs.html"
done

if [ -d "$tmpdir" ]; then
  rm -r "$tmpdir"
fi
