#!/bin/bash

help() {
   echo 'usage: firefoxium_rescue_tabs'
   echo '       firefoxium_rescue_tabs --help'
   echo
   echo '    Let the user choose which firefoxium tabs state to'
   echo '    save under ~/tmp/browsertabs'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

set -e          # stop on error
set -u          # stop on undefined variable
set -o pipefail # stop part of pipeline failing

firejail_browser_output=

cleanup() {
  [ "$firejail_browser_output" != "" ] && rm "$firejail_browser_output"
}

trap cleanup EXIT INT TERM

firejail_browser_output=`mktemp /tmp/foo-rescue_tabs_from_firejail.XXXXXX`
firejail_browser output_name | tee -a "$firejail_browser_output"
firejail_name=`tail -n 1 "$firejail_browser_output"`

browsertabs_home="$HOME/tmp/browsertabs"
cd "$browsertabs_home"
new_browsertabs_dir="$browsertabs_home/$( mkdir-now --full --ignore-existing --script )"
recovery_jsonlz4="$new_browsertabs_dir/recovery.jsonlz4"
firefoxium_cat_recovery $firejail_name > "$recovery_jsonlz4"
echo "saved in $( realpath "$recovery_jsonlz4" )"

