#!/bin/bash

help() {
   echo 'usage: google query'
   echo '       google --help'
   echo
   exit 1
}

[ "$1" == "--help" ] && help


if googleads-doubleclick allow; then
  block=true
else
  block=false
fi

bromium "https://google.com/?q=$1"

if [ "$block" == "true" ]; then
  googleads-doubleclick block
fi

