#!/bin/bash

help() {
   echo 'usage: google query'
   echo '       google --help'
   echo
   exit 1
}

[ "$1" == "--help" ] && help


sudo -- /home/tpo/bin/googleads-doubleclick allow

bromium "https://google.com/?q=$1"

sudo -- /home/tpo/bin/googleads-doubleclick block

