#!/bin/bash

help() {
   echo 'usage: google-wrap [arguments]'
   echo '       google-wrap --help'
   echo
   echo '   Wrap google web sites. google-wrap will:'
   echo
   echo '   * allow googleads-doubleclick access'
   echo '   * execute `bromium [arguments]`'
   echo '   * disallow googleads-doubleclick access'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

GOOGLEADS_DOUBLECLICK_BIN=$( command -v googleads-doubleclick )

sudo -- $GOOGLEADS_DOUBLECLICK_BIN allow

firefoxium "$@"

sudo -- $GOOGLEADS_DOUBLECLICK_BIN block

