#!/bin/bash

help() {
   echo 'usage: gtranslate'
   echo '       gtranslate --help'
   echo
   echo '   Access Google Translate'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

google-wrapper "https://translate.google.com"

