#!/bin/bash

help() {
   echo 'usage: kill_ssh destination'
   echo '       kill_ssh --help'
   echo
   echo '    kills ssh processes currenctly connecting to'
   echo '    the given destination'
   echo
   exit 1
}

[ "$1" == "--help" ] && help
[ "$1" == "" ] && echo "ERROR: you must give a destination as an argument" >&2 && exit 1

set -e          # stop on error
set -u          # stop on undefined variable
set -o pipefail # stop part of pipeline failing

pkill --full "ssh $1"
