#!/bin/bash

help() {
  echo 'usage: mairi _search _parameters'
  echo
  echo 'mairi searches your mail and displays results in mutt'
  echo
  echo 'mairi is a simple wrapper around mairix and mutt and accepts'
  echo 'the same parameters as mairix'
  echo 
  exit 1
}

[ "$1" == "--help" ] && help

# terminate if mairix doesn't find a message:
set -e

/usr/bin/mairix $@
sleep 1.5
mutt -f /home/tpo/mairix
