#!/bin/sh

help() {
  echo "$0 : list information on all currently installed kernel modules"
}

[ "$1" = "--help" ] && help && exit 1

for i in  `lsmod | sed '1d' | cut -d ' ' -f 1-2`; do
  /bin/echo -e "module:\t\t$i"
  /sbin/modinfo $i
  echo
done
