#!/bin/bash

help() {
  echo "usage: mount_encrypted image [mountpoint]"
  echo
  echo "    see also umount_encrypted"
  echo
  echo "    if mountpoint is not provided mounts under /media/image"
  echo
  exit 255
}

[ "$1" == "--help" ] || [ "$1" == "" ] && help

exit_err() {
  exit 1
}

unmkdir() {
  rmdir "$MNT"
  exit_err
}

unlosetup() {
  losetup -d $LOOP
  unmkdir
}

uncryptsetup() {
  cryptsetup remove $DEV_NAME
  unlosetup
}

IMG="$1"
DEV_NAME=$( realpath $IMG | tr -c '[:alnum:]' '_' )
if [ "$2" == "" ]; then
  # create mount point from image name
  # - replace forward slashes and '..' with underscores
  MNT=`echo "$IMG" | tr / _ | sed 's/\.\./__/g'`
  MNT="/media/$MNT"

  if [ -d "$MNT" ]; then
    echo "directory already exists"
    exit_err

  else
    if ! mkdir $MNT; then
      exit_err
    fi
  fi
else
  MNT="$2"
fi

LOOP=`losetup -f`
if ! losetup $LOOP "$IMG"; then
  unmkdir

else
  echo "cryptsetup create -c aes $DEV_NAME $LOOP"
  if ! cryptsetup create -c aes $DEV_NAME $LOOP; then
    unlosetup

  else
    if ! mount /dev/mapper/$DEV_NAME "$MNT"; then
      uncryptsetup

    else
      echo "image is mounted under $MNT"

    fi
  fi
fi
