#!/bin/bash

help() {
  echo "usage: mount_encrypted [options] image [mountpoint]"
  echo
  echo "    see also umount_encrypted"
  echo
  echo "    if mountpoint is not provided mounts under /media/image"
  echo
  echo "    --ro     mount read only"
  echo
  exit 255
}

[ "$1" == "--help" ] || [ "$1" == "" ] && help
[ "$1" == "--ro" ] && shift && RO="-o ro"

exit_err() {
  exit 1
}

unmkdir() {
  rmdir "$MNT"
  exit_err
}

unlosetup() {
  losetup -d $LOOP
  unmkdir
}

uncryptsetup() {
  cryptsetup remove $DEV_NAME
  unlosetup
}

IMG="$1"
DEV_NAME=$( realpath $IMG | tr -c '[:alnum:]' '_' )
if [ "$2" == "" ]; then
  # create mount point from image name
  # - replace forward slashes and '..' with underscores
  MNT=`echo "$IMG" | tr / _ | sed 's/\.\./__/g'`
  MNT="/media/$MNT"

  if [ -d "$MNT" ]; then
    echo "directory '$MNT' already exists ---"
    if [ "$( ls $MNT )" == "" ]; then
      echo "... and is empty, so we don't mind"
    else
      echo "--- and is NOT empty"
      exit_err
    fi

  else
    if ! mkdir $MNT; then
      exit_err
    fi
  fi
else
  MNT="$2"
fi

LOOP=`losetup -f`
if ! losetup $LOOP "$IMG"; then
  unmkdir

else
  cyptsetup_command="cryptsetup create -c aes $DEV_NAME $LOOP"
  crypt_setup=unknown

  crypto_dev_status="$( cryptsetup status $DEV_NAME $LOOP )"
  if [ "$?" == "0" ]; then
    echo "no need to execute '$cyptsetup_command' - $DEV_NAME $LOOP already exists"
    crypt_setup=ok
  else
    echo "cryptsetup create -c aes $DEV_NAME $LOOP"
    if ! cryptsetup create -c aes $DEV_NAME $LOOP; then
      unlosetup
      crypt_setup=not_ok
    else
      crypt_setup=ok
    fi
  fi

  if [ "$crypt_setup" == "ok" ]; then
    if ! mount $RO /dev/mapper/$DEV_NAME "$MNT"; then
      uncryptsetup
    else
      echo "image is mounted under $MNT"
    fi
  fi
fi
