#!/bin/bash

help() {
  echo "usage: mount_encrypted image [mountpoint]"
  echo
  echo "    see also umount_encrypted"
  echo
  echo "    if mountpoint is not provided mounts under /media/image"
  echo
  exit 255
}

[ "$1" == "--help" ] || [ "$1" == "" ] && help

IMG="$1"
DEV_NAME=$( realpath $IMG | tr -c '[:alnum:]' '_' )
if [ "$2" == "" ]; then
  # create mount point from image name
  # - replace forward slashes and '..' with underscores
  MNT=`echo "$IMG" | tr / _ | sed 's/\.\./__/g'`
  MNT="/media/$MNT"
  if ! mkdir $MNT; then
    exit 254
  fi
else
  MNT="$2"
fi
LOOP=`losetup -f`
losetup $LOOP "$IMG"
cryptsetup create -c aes $DEV_NAME $LOOP
mount /dev/mapper/$DEV_NAME "$MNT"

echo "image is mounted under $MNT"
