#!/bin/bash

help() {
  echo 'usage: music-dl URL'
  echo
  echo '    download URL from youtube, soundcloud etc. and transform to audio file'
  echo
  exit 1
}

[ "$1" == "--help" ] && help

# ?
#ffmpeg -i alt-J\ \(∆\)\ Breezeblocks.m4a -codec:v copy -codec:a libmp3lame -qscale:a 2 alt-J\ \(∆\)\ Breezeblocks.mp3
## http://superuser.com/questions/704493/ffmpeg-convert-m4a-files-to-mp3-without-significant-loss-of-information-quali

file=$( youtube-dl --title --get-filename "$1" )

youtube-dl --continue --title "$1"

type=$( file "$file" )

# check for known audio types
if   echo "$type" | grep -q "Audio file"; then
  true # do nothing
elif echo "$type" | grep -q "MPEG ADTS" ; then
  true # do nothing
else
  # extract audio
  youtube-dl --continue --title --extract-audio "$1"
fi

