#!/bin/bash

help() {
   echo 'usage: paw'
   echo
   echo '    wake up and restart all pulseaudio processes'
   echo
   echo '    See also: pas'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

pkill -CONT pulseaudio
# since I had multiple cases, where PA would not emit sound after
# restarting:
systemctl --user restart pulseaudio
