#!/bin/bash

help() {
   echo 'usage: paw'
   echo
   echo '    wake up all pulseaudio processes'
   echo
   echo '    See also: pas'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

pkill -CONT pulseaudio
