#!/bin/bash

help() {
   echo 'usage: psa [pattern]'
   echo
   echo '    Show all processes in full detail (ps auxw) excluding kernel'
   echo '    processes. If a pattern is given, then the process list is'
   echo "    grep'ed with that pattern."
   exit 1
}

[ "$1" == "--help" ] && help

if [ -z "$1" ]; then

   # Pattern of kernel process in `ps auxw` :
   # ... 0:00 [kthreadd]
   ps auxw | grep -v -P '\d:\d\d \[.*\]$'
else
   ps auxw | grep -v -P '\d:\d\d \[.*\]$' | grep "$1"
fi

