#!/bin/bash

help() {
   echo 'usage: psa [-w] [pattern]'
   echo
   echo '    Show all processes in full detail (ps faux) excluding kernel'
   echo '    processes. If a pattern is given, then the process list is'
   echo "    grep'ed with that pattern."
   echo
   echo '    psa will by default chop off long lines.'
   echo
   echo '    -w    wrap lines instead of chopping them off'
   echo
   echo '    psa depends on the 'linechop' tool.'
   exit 1
}

[ "$1" == "--help" ] && help
if [ "$1" == "-w" ]; then
   shift
   chopper="cat"
else
   chopper="linechop"
fi

if [ -z "$1" ]; then

   # Pattern of kernel process in `ps auxw` :
   # ... 0:00 [kthreadd]
   ps faux | grep -v -P '\d:\d\d \[.*\]$' | $chopper
else
   ps faux | grep -v -P '\d:\d\d \[.*\]$' | grep "$1" | $chopper
fi

