#!/bin/bash

help() {
   echo 'usage: rasa'
   echo '       rasa --help'
   echo
   echo '    Listen to Radio Rasa from the command line'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

mpv https://radio.upstream-cloud.ch/radiorasa-128.mp3
