#!/bin/bash

help() {
   echo 'usage: ssh-wait host'
   echo '       ssh-wait --help'
   echo
   echo '   wait for ssh to become available'
   exit 1
}

[ "$1" == "--help" ] && help
[ "$1" == "" ] && echo "ERROR: you need to provide a host name" && exit 2
HOST="$1"

slept=0
while ! ssh "$HOST" "exit 0"
do
    sleep 1
    slept=$(( $slept + 1 ))
    echo "Retry #$slept to connect to $HOST..."
done

set -e          # stop on error
set -u          # stop on undefined variable
set -o pipefail # stop part of pipeline failing
