#!/bin/bash

help() {
   echo 'usage: thunderbird-sleep'
   echo
   echo '    suspend all thunderbird processes'
   echo
   echo "    Note: it's advisable to add an 'alias tbs=thunderbird-sleep'"
   echo
   echo '    See also: thunderbird-wake'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

# Debian has icedove
# Ubuntu has thunderbird
pkill -STOP -f "(^|/)+icedove( |$)+"
pkill -STOP -f "(^|/)+thunderbird( |$)+"
