#!/bin/bash

help() {
   echo 'usage: thunderbird-sleep'
   echo
   echo 'suspend all thunderbird processes'
   echo
   echo 'See also: thunderbird-wake'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

pkill -STOP thunderbird
