#!/bin/bash

help() {
   echo 'usage: thunderbird-wake'
   echo
   echo '    wake up all thunderbird processes'
   echo
   echo "    Note: it's advisable to add an 'alias tbw=thunderbird-wake'"
   echo
   echo '    See also: thunderbird-sleep'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

pkill -CONT -f "(^|/)+icedove( |$)+"
pkill -CONT -f "(^|/)+thunderbird( |$)+"
