#!/bin/bash

help() {
   echo "copy arguments to clipboard (CTRL-V)"
   echo
   echo "usage: to_copy_args file_name arg1 arg2 ..."
   echo
   echo "  if no argument is given, then copy stdin to clipboard"
   exit 1
}

[ "$1" == "--help" ] && help

# "xargs echo -n" removes trailing newline
#
if [ "$1" != "" ]; then
  echo "$@" | xargs echo -n | xclip -i -selection clipboard
else
  xargs echo -n |xclip -i -selection clipboard
fi
