#!/bin/bash

help() {
   echo 'usage: to_jpg image.png [image.jpg]'
   echo
   echo '    transform png image to jpg format'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

jpg_name() {
  local filename="$1"
  base=$( basename "$1" .png )
  dir=$(  dirname  "$1" )
  [ -z "$dir" ] && dir="."

  echo "${dir}/${base}.jpg"
}

if [ "$2" == "" ]; then
  gm convert "$1" $( jpg_name "$1" )
else
  gm convert "$1" "$2"
fi
