#!/bin/bash

help() {
   echo 'usage: vimgrep (REGULAR_EXPRESSION|rg_option)+'
   echo '       vimgrep --help'
   echo
   echo '    will:'
   echo '      - use ripgrep (`rg`) to grep files'
   echo '      - display the result'
   echo '      - ask for confirmation'
   echo '      - edit the files with vim'
   echo
   echo '    You can set the VVV environment variable to'
   echo '    set options for vim:'
   echo
   echo '        VVV=-o vimgrep foo'
   echo
   echo '    Attention: this will run `rg` twice'
   echo
   exit 1
}

[ "$1" == "--help" -o "$1" == "" ] && help

echo
rg --color always "$@" 
echo

echo 'CTRL-C now if you do not want to edit the file(s) above or ENTER to continue.'
echo
echo 'once editing a file use `:cnext` to jump to the next occurence of the search string'

read answer

vim $VVV -q <(rg --vimgrep "$1")

