#!/bin/bash

help() {
   echo 'usage: whois_ip IP'
   echo '       whois_ip --help'
   echo
   echo '    will do a DNS lookup and a whois lookup on an IP'
   echo '    and filter out the relevant fields. Used as a'
   echo '    help tool to manually drop spammer IPs and'
   echo '    networks into a firewall'
   exit 1
}

[ "$1" == "--help" ] && help

host  "$1"
whois "$1" | grep -i "NetName\|Country\|Inetnum\|NetRange"
