#!/bin/bash

help() {
   echo 'usage: wping [--waitloop] [URL]'
   echo
   echo '    retrieves website via HTTP in order to see whether the web/internet'
   echo '    works. Default site is http://sourcepole.ch'
   echo
   echo '    --waitloop will silently loop until it can retrieve'
   echo '               the URL'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

if [ "$1" == "--waitloop" ]; then
  shift
  while ! wget ${1:-sourcepole.ch} -O /dev/null -q; do
    sleep 5
  done
fi
  
wget ${1:-sourcepole.ch} -O /dev/null
