#!/bin/bash

help() {
   echo 'usage: youtube ["youtube query"|URL]'
   echo '       youtube --help'
   echo
   echo '   Access youtube via `google-wrapper`'
   echo
   echo '   Depends on `google-wrapper`'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

# regex by Bernhard Barker, https://stackoverflow.com/a/19377429, thanks!
if [[ $1 =~ ^(https?\:\/\/)?(www\.)?(youtube\.com|youtu\.be)\/.+$ ]]; then
  google-wrapper "$1"
else
  google-wrapper "https://www.youtube.com/results?search_query=$@"
fi
