#!/bin/bash

help() {
   echo 'usage: youtube "youtube query"'
   echo '       youtube --help'
   echo
   exit 1
}

[ "$1" == "--help" ] && help

google-wrapper "https://www.youtube.com/results?search_query=$@"

